server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(ttf|woff|woff2|eot|otf)$ {
        add_header Access-Control-Allow-Origin *;
        expires 1y;
        access_log off;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 1y;
        access_log off;
    }
}
